// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWo8yH47EoKXSo7aUagyjZ5Nwm59O1sys',
    appId: '1:965274148830:web:426c89060beb14ba6c074f',
    messagingSenderId: '965274148830',
    projectId: 'flutter-devtest-bab32',
    authDomain: 'flutter-devtest-bab32.firebaseapp.com',
    databaseURL: 'https://flutter-devtest-bab32-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-devtest-bab32.appspot.com',
    measurementId: 'G-M2JXGEPZNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBkVIdIUBNL0L4tirIkqWuEtPasJn_KC0',
    appId: '1:965274148830:android:884a2a83b050b2946c074f',
    messagingSenderId: '965274148830',
    projectId: 'flutter-devtest-bab32',
    databaseURL: 'https://flutter-devtest-bab32-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-devtest-bab32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP4LkdCLE8LMqtttNkwViocnNEIMKaic0',
    appId: '1:965274148830:ios:1ad15902f388f5276c074f',
    messagingSenderId: '965274148830',
    projectId: 'flutter-devtest-bab32',
    databaseURL: 'https://flutter-devtest-bab32-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-devtest-bab32.appspot.com',
    iosClientId: '965274148830-nm6ah9bi2q1c4am6en1ccr3kocgi091u.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP4LkdCLE8LMqtttNkwViocnNEIMKaic0',
    appId: '1:965274148830:ios:1ad15902f388f5276c074f',
    messagingSenderId: '965274148830',
    projectId: 'flutter-devtest-bab32',
    databaseURL: 'https://flutter-devtest-bab32-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-devtest-bab32.appspot.com',
    iosClientId: '965274148830-nm6ah9bi2q1c4am6en1ccr3kocgi091u.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexExample',
  );
}
